<?xml version="1.0"?>
<package format="2">
  <name>thor_math</name>
  <version>0.1.0</version>
  <description>The thor_math package</description>


  <maintainer email="manuel.beschi@unibs.it">Manuel Beschi</maintainer>
  <maintainer email="nicola.pedrocchi@cnr.it">Nicola Pedrocchi</maintainer>


  <license>BSD-3-Clause</license>

  <buildtool_depend>cmake</buildtool_depend>
  <depend>eigen</depend>
  <depend>boost</depend>
  <depend>urdfdom</depend>
  <depend>urdfdom_headers</depend>
  <depend>pinocchio</depend>

  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <!-- Other tools can request additional information be placed here -->

  </export>
</package>
